[tools]
go = "latest"
ruby = "3"
python = "3.12"
usage = "latest"
node = "22"
"npm:vscode-langservers-extracted" = "latest"
"npm:gh-actions-language-server" = "latest"
java = "temurin"
"npm:prettier" = "latest"
"npm:git-open" = "latest"
"npm:typescript-language-server" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"pipx:python-lsp-server" = "latest"
ruff = "latest"
"npm:basedpyright" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"

[settings]
disable_hints = ["python_multi"]
experimental = true
